function New-DynamicRecord {
    <#
    .SYNOPSIS
        Creates an instance of the generated model class for a table (BUG-035).
    .DESCRIPTION
        Classes generated by New-DynamicModel / Export-DynamicModelsFromCatalog are only resolvable by name inside the
        scope that dot-sourced them, so callers cannot use New-Object or [TypeName]::new(). This factory constructs an
        instance from the [type] that Set-DynamicORMClass captured for the (database, table) pair. When the model is
        registered but not loaded yet, Set-DynamicORMClass is invoked first.
    .PARAMETER Table
        Table name the model was generated for.
    .PARAMETER Database
        Path of the SQLite database the model belongs to.
    .EXAMPLE
        Export-DynamicModelsFromCatalog -Database .\app.db | Out-Null
        Set-DynamicORMClass
        $asset = New-DynamicRecord -Table assets -Database .\app.db
        $asset.FindById(1).hostname()
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string]$Table,
        [Parameter(Mandatory)][string]$Database
    )

    $dbKey = Get-DynamicDatabaseKey -Database $Database
    $entry = $null
    if ($script:ModelRegistry -and $script:ModelRegistry.ContainsKey($dbKey) -and $script:ModelRegistry[$dbKey].ContainsKey($Table)) {
        $entry = $script:ModelRegistry[$dbKey][$Table]
    }
    if (-not $entry) {
        throw "No dynamic model is registered for table '$Table' in database '$Database'. Run Export-DynamicModelsFromCatalog (or New-DynamicModel) first."
    }

    $typeObj = $entry.Type
    if (-not $typeObj) {
        # Registered but not loaded yet: load the generated files, which captures the type objects
        Set-DynamicORMClass -Confirm:$false
        $typeObj = $script:ModelRegistry[$dbKey][$Table].Type
    }
    if (-not $typeObj) {
        $staticKey = $dbKey + '|' + $Table
        if ([DynamicActiveRecord]::DynamicModelTypes.ContainsKey($staticKey)) { $typeObj = [DynamicActiveRecord]::DynamicModelTypes[$staticKey] }
    }
    if (-not $typeObj) {
        throw "Dynamic model type '$($entry.TypeName)' for table '$Table' is not loaded. Run Set-DynamicORMClass first."
    }

    $ctorInfo = $typeObj.GetConstructor([type[]]@([string]))
    if (-not $ctorInfo) {
        throw "Dynamic model type '$($typeObj.Name)' has no ([string]) constructor."
    }
    return $ctorInfo.Invoke([object[]]@([string]$Database))
}
