# Module manifest for module 'PSCsvSQLiteORM'
#
# Generated by: Joey A Miles
#
# Generated on: 9/7/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSCsvSQLiteORM.psm1'

# Version number of this module.
ModuleVersion = '3.1.3'

# Supported PSEditions
CompatiblePSEditions = @('Desktop', 'Core')

# ID used to uniquely identify this module
GUID = '6109e160-fe6f-4fc3-87be-bb71db65bfd7'

# Author of this module
Author = 'Joey A Miles'

# Company or vendor of this module
CompanyName = 'SomeGuyDoingCoolStuff'

# Copyright statement for this module
Copyright = '(c) Joey A Miles. All rights reserved.'

# Description of the functionality provided by this module
Description = 'A SQLite ORM for Windows PowerShell 5.1 and PowerShell 7 with catalog, relationships, joins, upserts, and migrations.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ ModuleName = 'PSSQLite'; ModuleVersion = '1.1.0' })

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('SQLite', 'ORM', 'CSV', 'Database', 'DataImport', 'ActiveRecord', 'QueryBuilder', 'Migration')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/joeymiles/PSCsvSQLiteORM/blob/main/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/joeymiles/PSCsvSQLiteORM'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
Unreleased (since v3.1.3)
- DynamicActiveRecord Save, InsertMany, InsertOnConflict and BulkUpsert bind every column value under a
  positional parameter name (@p0..@pN), so record writes work for columns with spaces, dashes or other
  special characters; a failed insert now throws on Windows PowerShell 5.1 as well as on PowerShell 7
- Manifest declares both the Desktop and Core editions and pins PSSQLite 1.1.0 or later

v3.1.3
- Import-CsvToSqlite sanitizes SQL parameter names (alphanumeric characters and underscores only), so CSV
  files with spaces or special characters in their headers import without binding errors
- Note: this release did not change the DynamicActiveRecord write paths; see Unreleased above

v3.1.2
- Fixed SQLite version compatibility by replacing ON CONFLICT (UPSERT) syntax with traditional INSERT/UPDATE
- Supports older SQLite versions (< 3.24.0) that don't have UPSERT support
- Fixed catalog update functions for broader SQLite compatibility

v3.1.1
- Fixed PowerShell 5.1 compatibility by replacing null-coalescing operator (??) with conditional statements
- Resolved module import errors on Windows PowerShell 5.1

v3.1.0
- Added AppendOnly schema mode
- RIGHT/FULL join emulation support
- Settings script support for configuration
- Improved error handling and logging
'@

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}